### ISSUE TITLE
is not working in 5.2.3

### ISSUE THREAD

**Issue by karuppasamy20** [rednez/angular-user-idle#32]
index.js:176:5
TypeError: Object(...) is not a function

"@amcharts/amcharts3-angular": "^1.2.0",
    "@angular/animations": "^5.2.3",
    "@angular/common": "^5.2.3",
    "@angular/compiler": "^5.2.3",
    "@angular/core": "^5.2.3",
    "@angular/forms": "^5.2.3",
    "@angular/http": "^5.2.3",
    "@angular/platform-browser": "^5.2.3",
    "@angular/platform-browser-dynamic": "^5.2.3",
    "@angular/router": "^5.2.3",
    "angular-user-idle": "^2.0.0",
 "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.2.3",

**Comment by rednez** [comment]
Because do not support this version. Read requirements.
